# SPDX-FileCopyrightText: © 2025 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Samuel Gaist <samuel.gaist@idiap.ch>
#
# SPDX-License-Identifier: Apache-2.0

[metadata]
  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:conda:miniconda3:25.3.1:*:*:*:*:python:*:*"
    id = "miniconda3"
    name = "Miniconda.sh"
    uri = "https://repo.anaconda.com/miniconda/Miniconda3-py39_25.1.1-2-Linux-x86_64.sh"
    sha256 = "b40682cedf1e1755c02555f8d3d98aadb4607a68da7caf72a9bbe1fb9ae0b904"
    source = "https://github.com/conda/conda/archive/refs/tags/25.3.1.tar.gz"
    sha256_source = "5c6e41275154657189f169cbe02ed23b2fcb53491b457d00f8ca221603b2769b"
    stacks = ["*"]
    version = "25.3.1"

[[stacks]]
  id = "*"
