# SPDX-FileCopyrightText: © 2025 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Samuel Gaist <samuel.gaist@idiap.ch>
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["retrieval/go.mod", "retrieval/go.sum"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2013-Present CloudFoundry.org Foundation, Inc. All Rights Reserved."
SPDX-License-Identifier = "Apache-2.0"
